/**
 * The Air Soko station list.
 *
 * A Belgrade-based European carrier: a single hub at BEG, a regional focus
 * city at TIV for the summer coastal programme, a dense short- and medium-haul
 * European network, and five long-haul stations that give the wide-body fleet
 * something to do.
 *
 * Coordinates are airport reference points, accurate to a few hundred metres.
 * That is well inside what route distances and map rendering need, and far
 * outside anything navigational -- these numbers are for drawing and planning,
 * not for flying.
 *
 * The zone set is chosen to exercise the time handling rather than just to
 * look plausible: Europe/Belgrade and America/New_York change on different
 * dates, Asia/Kolkata sits at a half-hour offset, Asia/Dubai and Asia/Shanghai
 * never change at all, and America/Sao_Paulo is southern-hemisphere with DST
 * abolished. A schedule generator that is wrong about any of those is wrong
 * about this network.
 */

export interface SeedAirport {
  iataCode: string;
  icaoCode: string;
  name: string;
  city: string;
  countryCode: string;
  latitude: number;
  longitude: number;
  elevationFt: number;
  timeZone: string;
  isHub?: boolean;
  isFocusCity?: boolean;
}

export const SEED_AIRPORTS: readonly SeedAirport[] = [
  // --- Home ---------------------------------------------------------------
  {
    iataCode: "BEG",
    icaoCode: "LYBE",
    name: "Belgrade Nikola Tesla",
    city: "Belgrade",
    countryCode: "RS",
    latitude: 44.8184,
    longitude: 20.3091,
    elevationFt: 335,
    timeZone: "Europe/Belgrade",
    isHub: true,
  },
  {
    iataCode: "TIV",
    icaoCode: "LYTV",
    name: "Tivat",
    city: "Tivat",
    countryCode: "ME",
    latitude: 42.4047,
    longitude: 18.7233,
    elevationFt: 20,
    timeZone: "Europe/Podgorica",
    isFocusCity: true,
  },

  // --- Regional -----------------------------------------------------------
  {
    iataCode: "SJJ",
    icaoCode: "LQSA",
    name: "Sarajevo",
    city: "Sarajevo",
    countryCode: "BA",
    latitude: 43.8246,
    longitude: 18.3315,
    elevationFt: 1708,
    timeZone: "Europe/Sarajevo",
  },
  {
    iataCode: "SKP",
    icaoCode: "LWSK",
    name: "Skopje",
    city: "Skopje",
    countryCode: "MK",
    latitude: 41.9616,
    longitude: 21.6214,
    elevationFt: 781,
    timeZone: "Europe/Skopje",
  },
  {
    iataCode: "TIA",
    icaoCode: "LATI",
    name: "Tirana Nene Tereza",
    city: "Tirana",
    countryCode: "AL",
    latitude: 41.4147,
    longitude: 19.7206,
    elevationFt: 126,
    timeZone: "Europe/Tirane",
  },
  {
    iataCode: "ZAG",
    icaoCode: "LDZA",
    name: "Zagreb Franjo Tudman",
    city: "Zagreb",
    countryCode: "HR",
    latitude: 45.7429,
    longitude: 16.0688,
    elevationFt: 353,
    timeZone: "Europe/Zagreb",
  },
  {
    iataCode: "LJU",
    icaoCode: "LJLJ",
    name: "Ljubljana Joze Pucnik",
    city: "Ljubljana",
    countryCode: "SI",
    latitude: 46.2237,
    longitude: 14.4576,
    elevationFt: 1273,
    timeZone: "Europe/Ljubljana",
  },
  {
    iataCode: "SOF",
    icaoCode: "LBSF",
    name: "Sofia",
    city: "Sofia",
    countryCode: "BG",
    latitude: 42.6967,
    longitude: 23.4114,
    elevationFt: 1742,
    timeZone: "Europe/Sofia",
  },
  {
    iataCode: "OTP",
    icaoCode: "LROP",
    name: "Bucharest Henri Coanda",
    city: "Bucharest",
    countryCode: "RO",
    latitude: 44.5711,
    longitude: 26.085,
    elevationFt: 314,
    timeZone: "Europe/Bucharest",
  },
  {
    iataCode: "BUD",
    icaoCode: "LHBP",
    name: "Budapest Ferenc Liszt",
    city: "Budapest",
    countryCode: "HU",
    latitude: 47.4369,
    longitude: 19.2556,
    elevationFt: 495,
    timeZone: "Europe/Budapest",
  },

  // --- Western and central Europe -----------------------------------------
  {
    iataCode: "VIE",
    icaoCode: "LOWW",
    name: "Vienna International",
    city: "Vienna",
    countryCode: "AT",
    latitude: 48.1103,
    longitude: 16.5697,
    elevationFt: 600,
    timeZone: "Europe/Vienna",
  },
  {
    iataCode: "MUC",
    icaoCode: "EDDM",
    name: "Munich Franz Josef Strauss",
    city: "Munich",
    countryCode: "DE",
    latitude: 48.3538,
    longitude: 11.7861,
    elevationFt: 1487,
    timeZone: "Europe/Berlin",
  },
  {
    iataCode: "FRA",
    icaoCode: "EDDF",
    name: "Frankfurt am Main",
    city: "Frankfurt",
    countryCode: "DE",
    latitude: 50.0379,
    longitude: 8.5622,
    elevationFt: 364,
    timeZone: "Europe/Berlin",
  },
  {
    iataCode: "ZRH",
    icaoCode: "LSZH",
    name: "Zurich",
    city: "Zurich",
    countryCode: "CH",
    latitude: 47.4647,
    longitude: 8.5492,
    elevationFt: 1417,
    timeZone: "Europe/Zurich",
  },
  {
    iataCode: "CDG",
    icaoCode: "LFPG",
    name: "Paris Charles de Gaulle",
    city: "Paris",
    countryCode: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
    elevationFt: 392,
    timeZone: "Europe/Paris",
  },
  {
    iataCode: "AMS",
    icaoCode: "EHAM",
    name: "Amsterdam Schiphol",
    city: "Amsterdam",
    countryCode: "NL",
    latitude: 52.3105,
    longitude: 4.7683,
    elevationFt: -11,
    timeZone: "Europe/Amsterdam",
  },
  {
    iataCode: "BRU",
    icaoCode: "EBBR",
    name: "Brussels",
    city: "Brussels",
    countryCode: "BE",
    latitude: 50.9014,
    longitude: 4.4844,
    elevationFt: 184,
    timeZone: "Europe/Brussels",
  },
  {
    iataCode: "LHR",
    icaoCode: "EGLL",
    name: "London Heathrow",
    city: "London",
    countryCode: "GB",
    latitude: 51.4706,
    longitude: -0.4619,
    elevationFt: 83,
    timeZone: "Europe/London",
  },
  {
    iataCode: "PRG",
    icaoCode: "LKPR",
    name: "Prague Vaclav Havel",
    city: "Prague",
    countryCode: "CZ",
    latitude: 50.1008,
    longitude: 14.26,
    elevationFt: 1247,
    timeZone: "Europe/Prague",
  },
  {
    iataCode: "WAW",
    icaoCode: "EPWA",
    name: "Warsaw Chopin",
    city: "Warsaw",
    countryCode: "PL",
    latitude: 52.1657,
    longitude: 20.9671,
    elevationFt: 362,
    timeZone: "Europe/Warsaw",
  },

  // --- Southern Europe ----------------------------------------------------
  {
    iataCode: "FCO",
    icaoCode: "LIRF",
    name: "Rome Fiumicino",
    city: "Rome",
    countryCode: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
    elevationFt: 13,
    timeZone: "Europe/Rome",
  },
  {
    iataCode: "MXP",
    icaoCode: "LIMC",
    name: "Milan Malpensa",
    city: "Milan",
    countryCode: "IT",
    latitude: 45.6306,
    longitude: 8.7281,
    elevationFt: 768,
    timeZone: "Europe/Rome",
  },
  {
    iataCode: "BCN",
    icaoCode: "LEBL",
    name: "Barcelona El Prat",
    city: "Barcelona",
    countryCode: "ES",
    latitude: 41.2974,
    longitude: 2.0833,
    elevationFt: 12,
    timeZone: "Europe/Madrid",
  },
  {
    iataCode: "MAD",
    icaoCode: "LEMD",
    name: "Madrid Barajas",
    city: "Madrid",
    countryCode: "ES",
    latitude: 40.4719,
    longitude: -3.5626,
    elevationFt: 1998,
    timeZone: "Europe/Madrid",
  },
  {
    iataCode: "ATH",
    icaoCode: "LGAV",
    name: "Athens Eleftherios Venizelos",
    city: "Athens",
    countryCode: "GR",
    latitude: 37.9364,
    longitude: 23.9445,
    elevationFt: 308,
    timeZone: "Europe/Athens",
  },

  // --- Northern Europe ----------------------------------------------------
  {
    iataCode: "CPH",
    icaoCode: "EKCH",
    name: "Copenhagen Kastrup",
    city: "Copenhagen",
    countryCode: "DK",
    latitude: 55.618,
    longitude: 12.656,
    elevationFt: 17,
    timeZone: "Europe/Copenhagen",
  },
  {
    iataCode: "ARN",
    icaoCode: "ESSA",
    name: "Stockholm Arlanda",
    city: "Stockholm",
    countryCode: "SE",
    latitude: 59.6519,
    longitude: 17.9186,
    elevationFt: 137,
    timeZone: "Europe/Stockholm",
  },
  {
    iataCode: "OSL",
    icaoCode: "ENGM",
    name: "Oslo Gardermoen",
    city: "Oslo",
    countryCode: "NO",
    latitude: 60.1939,
    longitude: 11.1004,
    elevationFt: 681,
    timeZone: "Europe/Oslo",
  },

  // --- Long haul ----------------------------------------------------------
  {
    iataCode: "IST",
    icaoCode: "LTFM",
    name: "Istanbul",
    city: "Istanbul",
    countryCode: "TR",
    latitude: 41.2753,
    longitude: 28.7519,
    elevationFt: 325,
    timeZone: "Europe/Istanbul",
  },
  {
    iataCode: "DXB",
    icaoCode: "OMDB",
    name: "Dubai International",
    city: "Dubai",
    countryCode: "AE",
    latitude: 25.2532,
    longitude: 55.3657,
    elevationFt: 62,
    timeZone: "Asia/Dubai",
  },
  {
    iataCode: "BOM",
    icaoCode: "VABB",
    name: "Mumbai Chhatrapati Shivaji Maharaj",
    city: "Mumbai",
    countryCode: "IN",
    latitude: 19.0896,
    longitude: 72.8656,
    elevationFt: 39,
    timeZone: "Asia/Kolkata",
  },
  {
    iataCode: "PEK",
    icaoCode: "ZBAA",
    name: "Beijing Capital",
    city: "Beijing",
    countryCode: "CN",
    latitude: 40.0799,
    longitude: 116.6031,
    elevationFt: 116,
    timeZone: "Asia/Shanghai",
  },
  {
    iataCode: "JFK",
    icaoCode: "KJFK",
    name: "New York John F. Kennedy",
    city: "New York",
    countryCode: "US",
    latitude: 40.6413,
    longitude: -73.7781,
    elevationFt: 13,
    timeZone: "America/New_York",
  },
  {
    iataCode: "ORD",
    icaoCode: "KORD",
    name: "Chicago O'Hare",
    city: "Chicago",
    countryCode: "US",
    latitude: 41.9742,
    longitude: -87.9073,
    elevationFt: 672,
    timeZone: "America/Chicago",
  },
  {
    iataCode: "YYZ",
    icaoCode: "CYYZ",
    name: "Toronto Pearson",
    city: "Toronto",
    countryCode: "CA",
    latitude: 43.6777,
    longitude: -79.6248,
    elevationFt: 569,
    timeZone: "America/Toronto",
  },
  {
    iataCode: "GRU",
    icaoCode: "SBGR",
    name: "Sao Paulo Guarulhos",
    city: "Sao Paulo",
    countryCode: "BR",
    latitude: -23.4356,
    longitude: -46.4731,
    elevationFt: 2461,
    timeZone: "America/Sao_Paulo",
  },
];
