import { Router } from "express";
import { and, asc, eq, sql } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";
import { z } from "zod";
import {
  booleanFlagSchema,
  iataAirportCodeSchema,
  routeStatusSchema,
} from "@airsoko/contracts";
import { db } from "../../db/client.ts";
import { aircraftTypes, airports, recurringSchedules, routes } from "../../db/schema/index.ts";
import { requireAuth, requirePermission } from "../auth.ts";

/**
 * Routes: the reusable airport pairs.
 *
 * Read-only for now, which is the honest state of it. Routes are generated by
 * the seed from the commercial plan, and a route is the network planning
 * decision behind a schedule rather than something an operations controller
 * edits between flights -- so what Phase 3 needs from it is the ability to
 * pick one when filing a flight or a pattern, and nothing more. Creating and
 * suspending routes belongs with the network screens.
 *
 * Each row carries the count of patterns that fly it, which is what makes the
 * picker useful: an operator filing a new service wants the pairs the airline
 * already serves at the top, not an alphabetical list of everywhere.
 */

export const networkRouter: Router = Router();

const origin = alias(airports, "origin_airport");
const destination = alias(airports, "destination_airport");

const routeQuerySchema = z.object({
  /** Matches either code, either city, or the pair written as "BEG-VIE". */
  search: z.string().trim().max(80).optional(),
  originIata: iataAirportCodeSchema.optional(),
  destinationIata: iataAirportCodeSchema.optional(),
  status: routeStatusSchema.optional(),
  /** Only pairs a recurring schedule already flies. */
  scheduledOnly: booleanFlagSchema.optional(),
});

networkRouter.get("/", requireAuth, requirePermission("route:read"), async (req, res) => {
  const query = routeQuerySchema.parse(req.query);

  const conditions = [];
  if (query.originIata) conditions.push(eq(origin.iataCode, query.originIata));
  if (query.destinationIata) conditions.push(eq(destination.iataCode, query.destinationIata));
  if (query.status) conditions.push(eq(routes.status, query.status));
  if (query.search) {
    const needle = `%${query.search.toLowerCase()}%`;
    conditions.push(
      sql`(lower(${origin.iataCode}) like ${needle}
        or lower(${destination.iataCode}) like ${needle}
        or lower(${origin.city}) like ${needle}
        or lower(${destination.city}) like ${needle}
        or lower(${origin.iataCode} || '-' || ${destination.iataCode}) like ${needle})`,
    );
  }

  const rows = await db
    .select({
      id: routes.id,
      originId: origin.id,
      originIata: origin.iataCode,
      originName: origin.name,
      originCity: origin.city,
      originTimeZone: origin.timeZone,
      destinationId: destination.id,
      destinationIata: destination.iataCode,
      destinationName: destination.name,
      destinationCity: destination.city,
      destinationTimeZone: destination.timeZone,
      distanceNm: routes.distanceNm,
      blockMinutes: routes.blockMinutes,
      status: routes.status,
      typicalTypeCode: aircraftTypes.icaoTypeCode,
      typicalAircraftTypeId: routes.typicalAircraftTypeId,
      scheduleCount: sql<number>`(
        select count(*)::int from ${recurringSchedules}
        where ${recurringSchedules.routeId} = ${routes.id} and ${recurringSchedules.active}
      )`,
    })
    .from(routes)
    .innerJoin(origin, eq(origin.id, routes.originAirportId))
    .innerJoin(destination, eq(destination.id, routes.destinationAirportId))
    .leftJoin(aircraftTypes, eq(aircraftTypes.id, routes.typicalAircraftTypeId))
    .where(conditions.length > 0 ? and(...conditions) : undefined)
    .orderBy(asc(origin.iataCode), asc(destination.iataCode));

  const items = query.scheduledOnly ? rows.filter((row) => row.scheduleCount > 0) : rows;

  res.json({ items, total: items.length });
});
